version: '3'

services:

  laravel:
    image: evertonos2312/laravel:prod
    container_name: laravel
    networks:
      - laranet
  
  nginx:
    image: evertonos2312/nginx:prod
    container_name: nginx
    networks:
      - laranet
    ports:
      - "8080:80"
  
networks:
  laranet:
    driver: bridge